import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { DM_Sans as FontSans } from "next/font/google";
import Header from "@/components/header";
import { RoomWrapper } from "@/components/room-wrapper";

const fontSans = FontSans({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={fontSans.className}>
          <Header />
          <RoomWrapper>{children}</RoomWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
